### ISSUE TITLE
Cythonized build?

### ISSUE THREAD

**Issue by scw** [conda-forge/mistune-feedstock#9]
The current mistune package is pure Python, and doesn't rely on Cython for performance improvements.  I noticed this first in the downstream [Anaconda package](https://github.com/ContinuumIO/anaconda-issues/issues/9215), where older builds (>=0.7.3) did rely on Cython and emit per-platform builds. Is the desire here to retain this as a noarch package, or would adding Cython be acceptable for mistune? It adds [a bit of performance](https://github.com/lepture/mistune/issues/1) to the package, and is simple enough to implement. I'll submit a PR if this is a desired change.

**Comment by ocefpaf** [comment]
> or would adding Cython be acceptable for mistune? 

Totally acceptable. Can you send the PR?

**Comment by scw** [comment]
@ocefpaf cool, just submitted a PR. I did hit an issue with the [instructions for testing](https://conda-forge.org/docs/testing.html#run-docker-tests-locally-for-feedstock) against a local docker instance, but building the package locally on MacOS worked, as did on Windows.

**Comment by ocefpaf** [comment]
>  I did hit an issue with the instructions for testing against a local docker instance

Let us know if it is something we can fix.

> @ocefpaf cool, just submitted a PR

Thanks!

**Comment by ocefpaf** [comment]
Argh! The documentation is outdated b/c people keep moving things around. I'll fix that tomorrow, thanks!

The issue is mostly the docs BTW, sorry about that.

**Comment by scw** [comment]
No problem -- I was going to submit a PR for the docs, but thought the scope of the changes would span beyond just the leading `.` so left it be. Nice to see all the improvements in conda-forge since the last time I contributed!
